name: Calculator CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Basic check - list files
      - name: List project files
        run: ls -al

      # Step 3: Zip static files
      - name: Create zip of calculator site
        run: zip -r calculator.zip index.html style.css script.js

      # Step 4: Upload to AWS S3 (Optional)
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "./"

      # Step 5: Upload zip as artifact (optional)
      - name: Upload zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-artifact
          path: calculator.zip
